var data = {
    title: 'BIỂU ĐỒ 24H', 
    titleFont: '20pt Myriad Pro',
    titleStyle: 'Black',
    xLabel: '',
    yLabel: 'Nhiệt độ',
    labelFont: 'italic 12pt Adobe Ming Std L',
    labelStyle: '#000000',
    axisFont: '15pt Myriad Pro',
    axisStyle: '#000000',
    commentStyle: '#000000',
    splineStyle: 'red',
    maxNumberYAxic: 40,
    maxNumberXAxic: 24,
    dataPoints: [{ x: '-23', y: 10 },
                { x: '', y: 20 },
                { x: '', y: 2 },
                { x: '-20', y: 25 },
                { x: '', y: 8 },
                { x: '', y: 40 },
                { x: '', y: 17 },
                { x: '', y: 6 },
                { x: '', y: 3 },
                { x: '', y: 30 },
                { x: '', y: 36 },
                { x: '', y: 22 },
                { x: '', y: 11 },
                { x: '-10', y: 10 },
                { x: '', y: 9 },
                { x: '', y: 15.2 },
                { x: '', y: 7 },
                { x: '', y: 9 },
                { x: '', y: 5 },
                { x: '', y: 11 },
                { x: '', y: 3 },
                { x: '', y: 0 },
                { x: '', y: 1 },
                { x: '0', y: 0 }]
};